export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="agnoster-light"

plugins=(
	git,
	composer
)



source $ZSH/oh-my-zsh.sh


#--------------------------------------------------------------------------
# Aliases
#--------------------------------------------------------------------------


# Git

alias g="git"
alias gs="git s"
alias nah="git reset --hard;git clean -df"
alias co="git checkout"


# Docker
alias d="docker"
alias dc="docker compose"


